name: IslandFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.2
description: Plugin for the IslandFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, DisguiseCraft, BarAPI, CoreProtect]
authors: [reuben4545]

# plugin.yml is no longer used to define commands.
